apiVersion: apps/v2
kind: Deployment
metadata:
  name: nginx-deployment-qa
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-qa
        image: nginx:1.14.2
        ports:
        - containerPort: 80
