apiVersion: apps/v1
kind: Deployment
metadata:
  name: application_name-deployment
  labels:
    app: application_name
spec:
  replicas: replicas_count
  selector:
    matchLabels:
      app: application_name
  template:
    metadata:
      labels:
        app: application_name
    spec:
      containers:
      - name: application_name
        image: nginx:1.14.2
        ports:
        - containerPort: 80