# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    #- name: maven-settings-action
    #  uses: s4u/maven-settings-action@v2.4.1
    #  with:
    #    mirrors: '[{"id": "myid", "name": "myname", "mirrorOf": "myid", "url": "http://sample.com"}]'
    - name: Setup Maven 3
    # You may pin to the exact commit or the version.
    # uses: aahmed-se/setup-maven@814f5ba79a1f8c94a55a773bd53d0b618e54723b
      uses: stCarolas/setup-maven@v4.2
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
        maven-version: 3.6.1
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Docker Build & Push Action
    # You may pin to the exact commit or the version.
    # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        # Name of the Docker image
        image: SampleMaven
        # Tags override for Docker image
        tags: v1
        # Target Docker registry
        registry: mbabu00/samplemaven1
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: Dockerfile
        # Directory to run `docker build` from, if not project root
        #directory: # optional
        # Docker build arguments passed via --build-arg
        #buildArgs: # optional
        # Docker build labels passed via --label
        #labels: # optional
        # Docker build target passed via --target
        #target: # optional
        # Docker registry username
        #username: # optional
        # Docker registry password
        #password: # optional
        # GitHub organization to push image to (if not current)
        #gitHubOrg: # optional
        # Adds latest tag to auto-generated GitOps tag
        #addLatest: # optional, default is false
        # Suffixes a build timestamp to the branch-based Docker tag
        #addTimestamp: # optional, default is false
